# Generated by Django 4.2.5 on 2023-10-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.CharField(max_length=300, verbose_name='url картинки')),
                ('descr', models.CharField(max_length=500, verbose_name='Описание')),
                ('ovner', models.CharField(max_length=100, verbose_name='Основатель')),
                ('age', models.CharField(max_length=100, verbose_name='Годы существования')),
            ],
        ),
    ]
